server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/author_book_rest
    username: root
    password: root

  liquibase:
    change-log: classpath:/liquibase/changelog.xml

  jpa:
    show-sql: true
